title: Bitcoin setrið
email: your-email@example.com
description: >-
  Bitcoin setrið - Your description here
baseurl: ""
url: ""
twitter_username:
github_username:

markdown: kramdown
highlighter: rouge

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/